name: buildx

on:
  schedule:
    - cron:  '30 3 * * 6'
  push:
    branches: main

jobs:
  buildx:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate bake file for base
        run: |
          cat <<'EOF' > docker-bake-base.hcl
          group "default" {
              targets = [
                  "7_4",
                  "8_1",
                  "8_2"
              ]
          }
          target "default" {
              context="./php/"
              platforms = [
                  "linux/amd64",
                  "linux/arm64",
              ]
          }
          target "7_4" {
              inherits=["default"]
              dockerfile="Dockerfile"
              tags = [
                  "${{ vars.GITHUB_REPOSITORY_OWNER }}/php:7.4",
              ]
              args = {
                  PHP_VERSION="7.4"
              }
          }
          target "8_2" {
              inherits=["default"]
              dockerfile="Dockerfile"
              tags = [
                  "${{ vars.GITHUB_REPOSITORY_OWNER }}/php:8.2",
              ]
              args = {
                  PHP_VERSION="8.2"
              }
          }
          target "8_1" {
              inherits=["default"]
              dockerfile="Dockerfile"
              tags = [
                  "${{ vars.GITHUB_REPOSITORY_OWNER }}/php:8.1",
              ]
              args = {
                  PHP_VERSION="8.1"
              }
          }
          EOF
      -
        name: Build and push base
        uses: docker/bake-action@master
        with:
          push: true
          files: docker-bake-base.hcl
